london_underground_stations = [
    
  # Bakerloo line

  "Baker Street Underground Station",
	"Charing Cross Underground Station",
	"Edgware Road Underground Station",
	"Elephant & Castle Underground Station",
	"Embankment Underground Station",
	"Harlesden Underground Station",
	"Harrow & Wealdstone Underground Station",
	"Kensal Green Underground Station",
	"Kenton Underground Station",
	"Kilburn Park Underground Station",
	"Lambeth North Underground Station",
	"Maida Vale Underground Station",
	"Marylebone Underground Station",
	"North Wembley Underground Station",
	"Oxford Circus Underground Station",
	"Paddington Underground Station",
	"Piccadilly Circus Underground Station",
	"Queen’s Park Underground Station",
	"Regent’s Park Underground Station",
	"South Kenton Underground Station",
	"Stonebridge Park Underground Station",
	"Warwick Avenue Underground Station",
	"Waterloo Underground Station",
	"Wembley Central Underground Station",
	"Willesden Junction Underground Station",

  # Central line

  "Bank Underground Station",
	"Barkingside Underground Station",
	"Bethnal Green Underground Station",
	"Bond Street Underground Station",
	"Buckhurst Hill Underground Station",
	"Chancery Lane Underground Station",
	"Chigwell Underground Station",
	"Debden Underground Station",
	"Ealing Broadway Underground Station",
	"East Acton Underground Station",
	"Epping Underground Station",
	"Fairlop Underground Station",
	"Gants Hill Underground Station",
	"Grange Hill Underground Station",
	"Greenford Underground Station",
	"Hainault Underground Station",
	"Hanger Lane Underground Station",
	"Holborn Underground Station",
	"Holl Park Underground Station",
	"Lancaster Gate Underground Station",
	"Leyton Underground Station",
	"Leytonstone Underground Station",
	"Liverpool Street Underground Station",
	"Loughton Underground Station",
	"Marble Arch Underground Station",
	"Mile End Underground Station",
	"Newbury Park Underground Station",
	"North Acton Underground Station",
	"Northolt Underground Station",
	"Notting Hill Gate Underground Station",
	"Oxford Circus Underground Station",
	"Perivale Underground Station",
	"Queensway Underground Station",
	"Redbridge Underground Station",
	"Roding Valley Underground Station",
	"Ruislip Gardens Underground Station",
	"Shepherd’s Bush Underground Station",
	"Snaresbrook Underground Station",
	"South Ruislip Underground Station",
	"South Woodford Underground Station",
	"St. Paul’s Underground Station",
	"Stratford Underground Station",
	"Theydon Bois Underground Station",
	"Tottenham Court Road Underground Station",
	"Wanstead Underground Station",
	"West Acton Underground Station",
	"West Ruislip Underground Station",
	"White City Underground Station",
	"Woodford Underground Station",

  # Circle line

  "Aldgate Underground Station",
	"Baker Street Underground Station",
	"Barbican Underground Station",
	"Bayswater Underground Station",
	"Blackfriars Underground Station",
	"Cannon Street Underground Station",
	"Edgware Road Underground Station",
	"Embankment Underground Station",
	"Euston Square Underground Station",
	"Farringdon Underground Station",
	"Gloucester Road Underground Station",
	"Goldhawk Road Underground Station",
	"Great Portl Street Underground Station",
	"Hammersmith Underground Station",
	"High Street Kensington Underground Station",
	"King’s Cross St. Pancras Underground Station",
	"Ladbroke Grove Underground Station",
	"Latimer Road Underground Station",
	"Liverpool Street Underground Station",
	"Mansion House Underground Station",
	"Monument Underground Station",
	"Moorgate Underground Station",
	"Notting Hill Gate Underground Station",
	"Paddington Underground Station",
	"Royal Oak Underground Station",
	"Shepherd’s Bush Market Underground Station",
	"Sloane Square Underground Station",
	"South Kensington Underground Station",
	"St. James’s Park Underground Station",
	"Temple Underground Station",
	"Tower Hill Underground Station",
	"Victoria Underground Station",
	"Westbourne Park Underground Station",
	"Westminster Underground Station",
	"Wood Lane Underground Station",

  # District line

  "Acton Town Underground Station",
	"Aldgate East Underground Station",
	"Barking Underground Station",
	"Barons Court Underground Station",
	"Bayswater Underground Station",
	"Becontree Underground Station",
	"Blackfriars Underground Station",
	"Bow Road Underground Station",
	"Bromley-by-Bow Underground Station",
	"Cannon Street Underground Station",
	"Chiswick Park Underground Station",
	"Dagenham East Underground Station",
	"Dagenham Heathway Underground Station",
	"Ealing Broadway Underground Station",
	"Ealing Common Underground Station",
	"Earl’s Court Underground Station",
	"East Ham Underground Station",
	"East Putney Underground Station",
	"Edgware Road Underground Station",
	"Elm Park Underground Station",
	"Embankment Underground Station",
	"Fulham Broadway Underground Station",
	"Gloucester Road Underground Station",
	"Gunnersbury Underground Station",
	"Hammersmith Underground Station",
	"High Street Kensington Underground Station",
	"Hornchurch Underground Station",
	"Kensington (Olympia) Underground Station",
	"Kew Gardens Underground Station",
	"Mansion House Underground Station",
	"Mile End Underground Station",
	"Monument Underground Station",
	"Notting Hill Gate Underground Station",
	"Paddington Underground Station",
	"Parsons Green Underground Station",
	"Plaistow Underground Station",
	"Putney Bridge Underground Station",
	"Ravenscourt Park Underground Station",
	"Richmond Underground Station",
	"Sloane Square Underground Station",
	"South Kensington Underground Station",
	"Southfields Underground Station",
	"St. James’s Park Underground Station",
	"Stamford Brook Underground Station",
	"Stepney Green Underground Station",
	"Temple Underground Station",
	"Tower Hill Underground Station",
	"Turnham Green Underground Station",
	"Upminster Bridge Underground Station",
	"Upminster Underground Station",
	"Upney Underground Station",
	"Upton Park Underground Station",
	"Victoria Underground Station",
	"West Brompton Underground Station",
	"West Ham Underground Station",
	"West Kensington Underground Station",
	"Westminster Underground Station",
	"Whitechapel Underground Station",
	"Wimbledon Park Underground Station",
	"Wimbledon Underground Station",

  # Hammersmith & City line

  "Aldgate East Underground Station",
	"Baker Street Underground Station",
	"Barbican Underground Station",
	"Barking Underground Station",
	"Bow Road Underground Station",
	"Bromley-by-Bow Underground Station",
	"East Ham Underground Station",
	"Edgware Road Underground Station",
	"Euston Square Underground Station",
	"Farringdon Underground Station",
	"Goldhawk Road Underground Station",
	"Great Portl Street Underground Station",
	"Hammersmith Underground Station",
	"King's Cross St. Pancras Underground Station",
	"Ladbroke Grove Underground Station",
	"Latimer Road Underground Station",
	"Liverpool Street Underground Station",
	"Mile End Underground Station",
	"Moorgate Underground Station",
	"Paddington Underground"
  "Plaistow Underground Station",
	"Royal Oak Underground Station",
	"Shepherd's Bush Market Underground Station",
	"Stepney Green Underground Station",
	"Upton Park Underground Station",
	"West Ham Underground Station",
	"Westbourne Park Underground Station",
	"Whitechapel Underground Station",
	"Wood Lane Underground Station",

  # Jubilee line

  "Baker Street Underground Station",
	"Bermondsey Underground Station",
	"Bond Street Underground Station",
	"Canada Water Underground Station",
	"Canary Wharf Underground Station",
	"Canning Town Underground Station",
	"Canons Park Underground Station",
	"Dollis Hill Underground Station",
	"Finchley Road Underground Station",
	"Green Park Underground Station",
	"Kilburn Underground Station",
	"Kingsbury Underground Station",
	"London Bridge Underground Station",
	"Neasden Underground Station",
	"North Greenwich Underground Station",
	"Queensbury Underground Station",
	"Southwark Underground Station",
	"St. John’s Wood Underground Station",
	"Stanmore Underground Station",
	"Stratford Underground Station",
	"Swiss Cottage Underground Station",
	"Waterloo Underground Station",
	"Wembley Park Underground Station",
	"West Ham Underground Station",
	"West Hampstead Underground Station",
	"Westminster Underground Station",
	"Willesden Green Underground Station",

  # Metropolitan line

  "Aldgate Underground Station",
	"Amersham Underground Station",
	"Baker Street Underground Station",
	"Barbican Underground Station",
	"Chalfont & Latimer Underground Station",
	"Chesham Underground Station",
	"Chorleywood Underground Station",
	"Croxley Underground Station",
	"Eastcote Underground Station",
	"Euston Square Underground Station",
	"Farringdon Underground Station",
	"Finchley Road Underground Station",
	"Great Portl Street Underground Station",
	"Harrow-on-the-Hill Underground Station",
	"Hillingdon Underground Station",
	"Ickenham Underground Station",
	"King’s Cross St. Pancras Underground Station",
	"Liverpool Street Underground Station",
	"Moor Park Underground Station",
	"Moorgate Underground Station",
	"North Harrow Underground Station",
	"Northwick Park Underground Station",
	"Northwood Hills Underground Station",
	"Northwood Underground Station",
	"Pinner Underground Station",
	"Preston Road Underground Station",
	"Rayners Lane Underground Station",
	"Rickmansworth Underground Station",
	"Ruislip Manor Underground Station",
	"Ruislip Underground Station",
	"Uxbridge Underground Station",
	"Watford Underground Station",
	"Wembley Park Underground Station",
	"West Harrow Underground Station",
	"Willesden Green Underground Station",

  # Northern line

  "Angel Underground Station",
	"Archway Underground Station",
	"Balham Underground Station",
	"Bank Underground Station",
	"Battersea Power Station Underground Station",
	"Belsize Park Underground Station",
	"Borough Underground Station",
	"Brent Cross Underground Station",
	"Burnt Oak Underground Station",
	"Camden Town Underground Station",
	"Chalk Farm Underground Station",
	"Charing Cross Underground Station",
	"Clapham Common Underground Station",
	"Clapham North Underground Station",
	"Clapham South Underground Station",
	"Colindale Underground Station",
	"Colliers Wood Underground Station",
	"East Finchley Underground Station",
	"Edgware Underground Station",
	"Elephant & Castle Underground Station",
	"Embankment Underground Station",
	"Euston Underground Station",
	"FinchleyUnderground Station",
	"Golders Green Underground Station",
	"Goodge Street Underground Station",
	"Hampstead Underground Station",
	"Hendon Underground Station",
	"High Barnet Underground Station",
	"Highgate Underground Station",
	"Kennington Underground Station",
	"Kentish Town Underground Station",
	"King’s Cross St. Pancras Underground Station",
	"Leicester Square Underground Station",
	"London Bridge Underground Station",
	"Mill Hill East Underground Station",
	"Moorgate Underground Station",
	"Morden Underground Station",
	"Mornington Crescent Underground Station",
	"Nine Elms Underground Station",
	"Old Street Underground Station",
	"Oval Underground Station",
	"South Wimbledon Underground Station",
	"Stockwell Underground Station",
	"Tooting Bec Underground Station",
	"Tooting Broadway Underground Station",
	"Tottenham Court Road Underground Station",
	"Totteridge & Whetstone Underground Station",
	"Tufnell Park Underground Station",
	"Warren Street Underground Station",
	"Waterloo Underground Station",
	"West Finchley Underground Station",
	"Woodside Park Underground Station",

  # Piccadilly line

  "Acton Town Underground Station",
	"Alperton Underground Station",
	"Arnos Grove Underground Station",
	"Arsenal Underground Station",
	"Barons Court Underground Station",
	"Boston Manor Underground Station",
	"Bounds Green Underground Station",
	"Caledonian Road Underground Station",
	"Cockfosters Underground Station",
	"Covent Garden Underground Station",
	"Ealing Common Underground Station",
	"Earl's Court Underground Station",
	"Eastcote Underground Station",
	"Finsbury Park Underground Station",
	"Gloucester Road Underground Station",
	"Green Park Underground Station",
	"Hammersmith Underground Station",
	"Hatton Cross Underground Station",
	"Heathrow Terminal 4 Underground Station",
	"Heathrow Terminal 5 Underground Station",
	"Heathrow Terminals 2 & 3 Underground Station",
	"Hillingdon Underground Station",
	"Holborn Underground Station",
	"Holloway Road Underground Station",
	"Hounslow Central Underground Station",
	"Hounslow East Underground Station",
	"Hounslow West Underground Station",
	"Hyde Park Corner Underground Station",
	"Ickenham Underground Station",
	"King's Cross St. Pancras Underground Station",
	"Knightsbridge Underground Station",
	"Leicester Square Underground Station",
	"Manor House Underground Station",
	"North Ealing Underground Station",
	"Northfields Underground Station",
	"Oakwood Underground Station",
	"Osterley Underground Station",
	"Park Royal Underground Station",
	"Piccadilly Circus Underground Station",
	"Rayners Lane Underground Station",
	"Ruislip Manor Underground Station",
	"Ruislip Underground Station",
	"Russell Square Underground Station",
	"South Ealing Underground Station",
	"South Harrow Underground Station",
	"South Kensington Underground Station",
	"Southgate Underground Station",
	"Sudbury Hill Underground Station",
	"Sudbury Town Underground Station",
	"Turnham Green Underground Station",
	"Turnpike Lane Underground Station",
	"Uxbridge Underground Station",
	"Wood Green Underground Station",

  # Victoria line

  "Blackhorse Road Underground Station",
	"Brixton Underground Station",
	"Euston Underground Station",
	"Finsbury Park Underground Station",
	"Green Park Underground Station",
	"Highbury & Islington Underground Station",
	"King's Cross St. Pancras Underground Station",
	"Oxford Circus Underground Station",
	"Pimlico Underground Station",
	"Seven Sisters Underground Station",
	"Stockwell Underground Station",
	"Tottenham Hale Underground Station",
	"Vauxhall Underground Station",
	"Victoria Underground Station",
	"Walthamstow Central Underground Station",
	"Warren Street Underground Station",

  # Waterloo & City line

  "Bank Underground Station",
  "Waterloo Underground Station"

  # Dockland Light Rail

  "Abbey Road Station",
	"All Saints Station",
	"Bank Station",
	"Beckton Station",
	"Beckton Park Station",
	"Blackwall Station",
	"Bow Church Station",
	"Canary Wharf Station",
	"Canning Town Station",
	"Crossharbour Station",
	"Custom House (for ExCel) Station",
	"Cutty Sark (for Maritime Greenwich) Station",
	"Cyprus Station",
	"Deptford Bridge Station",
	"Devons Road Station",
	"East India Station",
	"Elverson Road Station",
	"Gallions Reach Station",
	"Greenwich Station",
	"Heron Quays Station",
	"Island Gardens Station",
	"King George V Station",
	"Langdon Park Station",
	"Lewisham Station",
	"Limehouse Station",
	"London City Airport Station",
	"Mudchute Station",
	"Pontoon Dock Station",
	"Poplar Station",
	"Prince Regent Station",
	"Pudding Mill Lane Station",
	"Royal Albert Station",
	"Royal Victoria Station",
	"Shadwell Station",
	"South Quay Station",
	"Star Lane Station",
	"Stratford Station",
	"Stratford High Street Station",
	"Stratford International Station",
	"Tower Gateway Station",
	"West Ham Station",
	"West India Quay Station",
	"West Silvertown Station",
	"Westferry Station",
	"Woolwich Arsenal Station",

  # Elizabeth line

  "Abbey Wood",
	"Acton Main Line Rail Station",
	"Bond Street",
	"Brentwood Rail Station",
	"Burnham (Berks) Rail Station",
	"Canary Wharf",
	"Chadwell Heath Rail Station",
	"Custom House",
	"Ealing Broadway Rail Station",
	"Farringdon",
	"Forest Gate Rail Station",
	"Gidea Park Rail Station",
	"Goodmayes Rail Station",
	"Hanwell Rail Station",
	"Harold Wood Rail Station",
	"Hayes & Harlington Rail Station",
	"Heathrow Terminal 4 Rail Station",
	"Heathrow Terminal 5 Rail Station",
	"Heathrow Terminals 2 & 3 Rail Station",
	"Ilford Rail Station",
	"Iver Rail Station",
	"Langley (Berks) Rail Station",
	"Liverpool Street",
	"Maidenhead Rail Station",
	"Manor Park Rail Station",
	"Maryl Rail Station",
	"Paddington",
	"Reading Rail Station",
	"Romford Rail Station",
	"Seven Kings Rail Station",
	"Shenfield Rail Station",
	"Slough Rail Station",
	"Southall Rail Station",
	"Stratford (London) Rail Station",
	"Taplow Rail Station",
	"Tottenham Court Road",
	"Twyford Rail Station",
	"West Drayton Rail Station",
	"West Ealing Rail Station",
	"Whitechapel",
	"Woolwich",
	"Liverpool Street Rail Station",

  # Liberty line

  "Emerson Park Rail Station",
  "Romford Rail Station",
  "Upminister Rail Station"

  # Lioness line

  "Bushey Rail Station",
	"Carpenders Park Rail Station",
	"Harlesden Rail Station",
	"Harrow & Wealdstone Rail Station",
	"Hatch End Rail Station",
	"Headstone Lane Rail Station",
	"Kensal Green Rail Station",
	"Kenton Rail Station",
	"Kilburn High Road Rail Station",
	"London Euston Rail Station",
	"North Wembley Rail Station",
	"Queens Park (London) Rail Station",
	"South Hampstead Rail Station",
	"South Kenton Rail Station",
	"Stonebridge Park Rail Station",
	"Watford High Street Rail Station",
	"Watford Junction Rail Station",
	"Wembley Central Rail Station",
	"Willesden Junction Rail Station",

  # Mildmay line

  "Acton Central Rail Station",
	"Brondesbury Park Rail Station",
	"Brondesbury Rail Station",
	"Caledonian Road & Barnsbury Rail Station",
	"Camden Road Rail Station",
	"Canonbury Rail Station",
	"Clapham Junction Rail Station",
	"Dalston Kingsland Rail Station",
	"Finchley Road & Frognal Rail Station",
	"Gospel Oak Rail Station",
	"Gunnersbury Rail Station",
	"Hackney Central Rail Station",
	"Hackney Wick Rail Station",
	"Hampstead Heath Rail Station",
	"Highbury & Islington Rail Station",
	"Homerton Rail Station",
	"Imperial Wharf Rail Station",
	"Kensal Rise Rail Station",
	"Kensington (Olympia) Rail Station",
	"Kentish Town West Rail Station",
	"Kew Gardens Rail Station",
	"Richmond (London) Rail Station",
	"Shepherds Bush Rail Station",
	"South Acton Rail Station",
	"Stratford (London) Rail Station",
	"West Brompton Rail Station",
	"West Hampstead Rail Station",
	"Willesden Junction Rail Station",

  # Suffragette line

  "Barking Rail Station",
	"Barking Riverside",
  "Blackhorse Road Rail Station",
	"Crouch Hill Rail Station",
	"Gospel Oak Rail Station",
  "Harringay Green Lanes Rail Station",
	"Leyton Midland Road Rail Station",
	"Leytonstone High Road Rail Station",
	"South Tottenham Rail Station",
	"Upper Holloway Rail Station",
	"Walthamstow Queens Road Rail Station",
	"Wanstead Park Rail Station",
	"Woodgrange Park Rail Station",

  # Tram line

  "Addington Village Tram Stop",
	"Addiscombe Tram Stop",
	"Ampere Way Tram Stop",
	"Arena Tram Stop",
	"Avenue Road Tram Stop",
	"Beckenham Junction Tram Stop",
	"Beckenham Road Tram Stop",
	"Beddington Lane Tram Stop",
	"Belgrave Walk Tram Stop",
	"Birkbeck Tram Stop",
	"Blackhorse Lane Tram Stop",
	"Centrale Tram Stop",
	"Church Street Tram Stop",
	"Coombe Lane Tram Stop",
	"Dundonald Road Tram Stop",
	"East Croydon Tram Stop",
	"Elmers End Tram Stop",
	"Fieldway Tram Stop",
	"George Street Tram Stop",
	"Gravel Hill Tram Stop",
	"Harrington Road Tram Stop",
	"King Henry's Drive Tram Stop",
	"Lebanon Road Tram Stop",
	"Lloyd Park Tram Stop",
	"Merton Park Tram Stop",
	"Mitcham Junction Tram Stop",
	"Mitcham Tram Stop",
	"Morden Road Tram Stop",
	"New Addington Tram Stop",
	"Phipps Bridge Tram Stop",
	"Reeves Corner Tram Stop",
	"Sandilands Tram Stop",
	"Therapia Lane Tram Stop",
	"Waddon Marsh Tram Stop",
	"Wandle Park Tram Stop",
	"Wellesley Road Tram Stop",
	"West Croydon Tram Stop",
	"Wimbledon Tram Stop",
	"Woodside Tram Stop",

  # Weaver line

  "Bethnal Green Rail Station",
	"Bruce Grove Rail Station",
	"Bush Hill Park Rail Station",
	"Cambridge Heath (London) Rail Station",
	"Cheshunt Rail Station",
	"Chingford Rail Station",
	"Clapton Rail Station",
	"Edmonton Green Rail Station",
	"Enfield Town Rail Station",
	"Hackney Downs Rail Station",
	"Highams Park Rail Station",
	"London Fields Rail Station",
	"London Liverpool Street Rail Station",
	"Rectory Road Rail Station",
	"Seven Sisters Rail Station",
	"Silver Street Rail Station",
	"Southbury Rail Station",
	"St James Street (London) Rail Station",
	"Stamford Hill Rail Station",
	"Stoke Newington Rail Station",
	"Theobalds Grove Rail Station",
	"Turkey Street Rail Station",
	"Walthamstow Central Rail Station",
	"White Hart Lane Rail Station",
	"Wood Street Rail Station",

  # Windrush line

  "Anerley Rail Station",
	"Brockley Rail Station",
	"Canada Water Rail Station",
	"Canonbury Rail Station",
	"Clapham High Street Rail Station",
	"Clapham Junction Rail Station",
	"Crystal Palace Rail Station",
	"Dalston Junction Rail Station",
	"Denmark Hill Rail Station",
	"Forest Hill Rail Station",
	"Haggerston Rail Station",
	"Highbury & Islington Rail Station",
	"Honor Oak Park Rail Station",
	"Hoxton Rail Station",
	"New Cross ELL Rail Station",
	"New Cross Gate Rail Station",
	"Norwood Junction Rail Station",
	"Peckham Rye Rail Station",
	"Penge West Rail Station",
	"Queens Road Peckham Rail Station",
	"Rotherhithe Rail Station",
	"Shadwell Rail Station",
	"Shoreditch High Street Rail Station",
	"Surrey Quays Rail Station",
	"Sydenham Rail Station",
	"Wsworth Road Rail Station",
	"Wapping Rail Station",
	"West Croydon Rail Station",
	"Whitechapel Rail Station",
]

